# Gauss Elimination Method

In [14]:
import numpy as np

def gauss_elimination(A, b):
    # Combine A and b into an augmented matrix
    n = len(b)
    augmented_matrix = np.hstack([A, b.reshape(-1, 1)])
    
    if (np.linalg.det(A) == 0):
        raise Exception("System of linear equation is singluar and not solvable")

    # Forward Elimination
    for i in range(n):
        # Make the diagonal contain all 1s
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i][i]
        
        # Make the elements below the pivot elements 0
        for j in range(i+1, n):
            factor = augmented_matrix[j][i]
            print(augmented_matrix)
            augmented_matrix[j] = augmented_matrix[j] - factor * augmented_matrix[i]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = augmented_matrix[i][-1] - np.dot(augmented_matrix[i][i+1:n], x[i+1:n])

    return x

# Example Usage
A = np.array([[1, 2, 3], 
              [2, 6, 102], 
              [4, -8, 4]], dtype=float)
b = np.array([10, 4, 8], dtype=float)

solution = gauss_elimination(A, b)
print("Solution:", solution)


[[  1.   2.   3.  10.]
 [  2.   6. 102.   4.]
 [  4.  -8.   4.   8.]]
[[  1.   2.   3.  10.]
 [  0.   2.  96. -16.]
 [  4.  -8.   4.   8.]]
[[  1.   2.   3.  10.]
 [  0.   1.  48.  -8.]
 [  0. -16.  -8. -32.]]
Solution: [ 6.42105263  2.10526316 -0.21052632]


Solution: [3. 1. 2.]
